Docs initial setup revamp
Start9Labs/documentation pull request #217
Opened 2022-12-12 07:25 UTC by gStart9

2022-12-12 16:14 UTC, kn0wmad commented
Need to add the new video at the top of this page - ask @BitcoinMechanic if you need the link

2022-12-12 21:54 UTC, BitcoinMechanic commented
The video isn't complete yet, I will add it once it is.

2022-12-14 00:59 UTC, kn0wmad requested changes

2022-12-14 00:59 UTC, kn0wmad commented on site/source/user-manual/initial-setup.rst
> +   - An ethernet network with DHCP server must be unavailable at setup.  Most routers provide one.  If such ethernet connectivity is not available, or there is another hardware issue, you may hear th
available, not unavailable

2022-12-14 01:00 UTC, kn0wmad approved these changes

2022-12-14 03:50 UTC, merged