lan-chrome-brave instructions touchups
Start9Labs/documentation pull request #274
Opened 2023-01-17 05:19 UTC by gStart9

2023-01-17 16:32 UTC, kn0wmad requested changes

2023-01-17 16:32 UTC, kn0wmad commented on site/source/user-manual/connecting/connecting-lan/lan-browser/lan-chrome-brave.rst
>  =========================
It's dumb, but these `====` need to be extended to end of line at top and bottom or we'll get RST warnings in our builds

2023-01-17 19:12 UTC, gStart9 commented
Thanks for catching that.  Fixed with latest push.

2023-01-18 00:06 UTC, kn0wmad approved these changes

2023-01-18 02:00 UTC, merged