Modernize Synapse instructions
Start9Labs/documentation pull request #347
Opened 2023-04-01 20:37 UTC by gStart9

2023-04-02 22:32 UTC, kn0wmad requested changes
Mainly notes on index page

2023-04-02 22:32 UTC, kn0wmad commented on site/source/user-manual/service-guides/matrix/index.rst
> +Synapse is a self-hosted Matrix server, capable of federation with the wider matrix network (but only .onion for now).
```suggestion
Synapse is a self-hosted Matrix server, capable of federation with the wider Matrix network (but only .onion for now).
```

2023-04-02 22:32 UTC, kn0wmad commented on site/source/user-manual/service-guides/matrix/index.rst
> +.. _synapse-service:
As the "Matrix Index," I think this should be labeled as such, then files in this directory can be for services/clients, i.e. Synapse, Conduit, etc

2023-04-02 22:32 UTC, kn0wmad commented on site/source/user-manual/service-guides/matrix/synapse.rst
> +  **Substep 1**: In your Synapse dashboard, click "Launch UI"
Maybe check how 'substeps' are done elsewhere.  I think I normally turn them into dashed lists, but it's possible we have used 1a., 1b., etc type listing

2023-04-18 17:05 UTC, gStart9 commented
I actually either want to scrap this change to the docs and just have the instructions updated in the Synapse wrapper:
https://github.com/Start9Labs/synapse-wrapper/pull/58

Or I want the synapse wrapper's instructions to point to the docs where we explain everything there and nothing in that step of the instructions.

@k0gen Can you review my PR?  Do you like it for the Synapse wrapper?

2023-04-18 20:12 UTC, kn0wmad commented
Okay, sounds like this can be closed then?

2023-04-19 18:17 UTC, closed without merging