Windows users can use command-line ssh instructions
Start9Labs/documentation pull request #382
Opened 2023-05-15 17:44 UTC by gStart9

2023-05-15 20:50 UTC, kn0wmad approved these changes
Nice!

2023-05-15 20:59 UTC, kn0wmad requested changes

2023-05-15 20:59 UTC, kn0wmad commented on site/source/user-manual/ssh.rst
> +Following the commands above for Windows should get you in.  However, if you prefer a GUI tool, `BrewsBitcoin <https://brewsbitcoin.com>`_ has created `a guide for connecting via SSH using PuTTY on W
```suggestion
Following the commands above for Windows will get you in.  However, if you prefer a GUI tool, `BrewsBitcoin <https://brewsbitcoin.com>`_ has created `a guide for connecting via SSH using PuTTY on Windows. <https://medium.com/@brewsbitcoin/ssh-to-start9-embassy-from-windows-4a4e17891b5a>`_
```

2023-05-17 05:34 UTC, gStart9 commented
I guess there's no way to just accept a changes and consider it reviewed.  Weird.  I await your "review" then.

2023-05-17 19:24 UTC, merged