Add instructions to mount and inspect encrypted backups
Start9Labs/documentation pull request #425
Opened 2023-07-03 23:48 UTC by gStart9

2023-07-03 23:49 UTC, gStart9 commented
Do we need more explicit instructions for copying files from the backups to eg. `/embassy-data/package-data/volumes/*/*`?

2023-07-05 17:02 UTC, kn0wmad requested changes
Sorry to butcher this one up, but I want to convey that this is not for normie use

2023-07-05 17:02 UTC, kn0wmad commented on site/source/user-manual/backups/backup-mount.rst
> +In order to inspect the contents of an encrypted Start9 server backup, you first need to create a backup to mount and inspect.
```suggestion
    .. warning:: The following are advanced tools and using them is only advised when under the instruction of a Start9 Support Technician.  USE AT YOUR OWN RISK - these operations are not supported outside of the context of support.
```

2023-07-05 17:03 UTC, kn0wmad commented
> Do we need more explicit instructions for copying files from the backups to eg. `/embassy-data/package-data/volumes/*/*`?

No, just basic documentation is fine, thanks

2023-07-06 14:34 UTC, kn0wmad approved these changes

2023-07-06 14:35 UTC, merged