Hardware Upgrade Section Refactor and General Maintenance
Start9Labs/documentation pull request #430
Opened 2023-07-08 00:56 UTC by kn0wmad

2023-07-10 22:03 UTC, gStart9 requested changes

2023-07-10 22:03 UTC, gStart9 commented on site/source/user-manual/upgrade-hardware/naspi-ssd-upgrade.rst
>  ================
```suggestion
======================
```

2023-07-10 22:03 UTC, gStart9 commented on site/source/user-manual/upgrade-hardware/naspi-ssd-upgrade.rst
>  ================
```suggestion
======================
```

2023-07-11 04:09 UTC, kn0wmad commented
FYI - you can select multiple lines for suggested edits

2023-07-11 15:25 UTC, gStart9 approved these changes

2023-07-11 15:38 UTC, merged