documentation-github-flow-update
Start9Labs/documentation pull request #464
Opened 2023-08-08 14:57 UTC by 13Homer13

Updated flow and screenshots for github documentation.

2023-08-16 14:58 UTC, kn0wmad requested changes

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        #. Tap "new pull request" by the side of the branch you just created:
```suggestion
        #. Click "Compare & pull request" in the yellow box (if this does not appear, go to "Pull Requests -> New"):
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        #. Once reviewed we will either suggest changes or approve it if no changes are necessary. If we reject your PR we will try to offer an explanation of why the PR was not needed.
```suggestion
        #. From here, a Start9 team member will review your PR, either suggesting changes or approving it if no changes are necessary.
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        2. Name and enter the contents of your first article and then tap "Commit changes".
```suggestion
        2. Name and enter the contents of your first article and then click "Commit changes".  Remember to put this in the correct location in the file structure.
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        3. Describe your article in the first field, tap "Create new branch for this commit and start a pull request," name the branch in the second field and tap "Propose new file".
```suggestion
        3. Describe your article in the first field, click "Create new branch for this commit and start a pull request," name the branch in the second field and click "Propose new file".
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        4. Now tap "documentation" and you will likely see this "Compare and pull request" button - if so tap it and head to the next step.
```suggestion
        4. Now click "documentation" and then click the "Compare and pull request" button.  If this option does not appear, see the note below.
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +            If you don't see "Compare & pull request" button, then tap "branches" instead, then tap "New pull request" next to the branch you created.
```suggestion
            If you don't see the "Compare & pull request" button, click "branches", then click "New pull request" next to the branch you created.
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        5. Now ensure that the base repository is Start9Labs/documentation, then finally tap "Create pull request".
```suggestion
        5. Ensure that the base repository is Start9Labs/documentation, then click "Create pull request".
```

2023-08-16 14:58 UTC, kn0wmad commented on site/source/developer-docs/documentation.rst
> +        6. Once reviewed we will either suggest changes or approve it if no changes are necessary. If we reject your PR we will try to offer an explanation of why the PR was not needed.
```suggestion
        6. From here, a Start9 team member will review your PR, either suggesting changes or approving it if no changes are necessary.
```

2023-08-16 14:59 UTC, kn0wmad commented
Closes #449

2023-08-17 06:55 UTC, 13Homer13 commented on site/source/developer-docs/documentation.rst
> +#. Fork the repository by taping here:
Yeah I will keep in mind.

2023-08-17 18:47 UTC, kn0wmad approved these changes

2023-08-17 18:47 UTC, merged