Update firmware links in docs and add StartOS proviso
Start9Labs/documentation pull request #545
Opened 2023-11-15 19:30 UTC by gStart9

2023-11-15 19:35 UTC, kn0wmad commented
On hold pending firmware testing

2023-11-15 21:37 UTC, gStart9 commented
The firmware works!

2023-11-17 21:34 UTC, kn0wmad requested changes

2023-11-17 21:34 UTC, kn0wmad commented on site/source/flashing-guides/firmware-pure.rst
> +If you're about to install StartOS, you do not need to manually flash your device using this guide, as the latest firmware that was available when StartOS was most recently released is embedded in th
```suggestion
Generally, you do not need to manually flash your device using this guide, as the firmware is now automatically updated on supported devices.  Please only use this method if directed by a Start9 Support Technician.
```

2023-11-21 18:01 UTC, kn0wmad approved these changes

2023-11-27 03:56 UTC, merged