bitbox-integration
Start9Labs/documentation pull request #571
Opened 2023-12-27 12:01 UTC by 13Homer13

I added bitbox guide to bitcoin integrations.

2023-12-28 16:28 UTC, 13Homer13 commented
I think I can add note that only connecting node via tor is available?

2023-12-29 00:23 UTC, gStart9 commented
I think if we're going to insert bitbox, we need our own guide.  It should be easy to adapt from theirs since it's already mostly done, but a few things like where to look in the StartOS Web UI for your electrum address need to be added in, otherwise this guide may cause more support rather than less.

2023-12-29 16:40 UTC, kn0wmad commented
At some point, we'll eventually need to generalize our guides.  It's not going to remain possible to maintain guides for all possible third party software.  For now, it may warrant a quick "add electrs to this field, in this format, etc" - with a link to their guide.

2024-01-02 01:36 UTC, kn0wmad requested changes

2024-01-02 01:36 UTC, kn0wmad commented on site/source/service-guides/bitcoin/bitcoin-integrations.rst
> +#. Then restart the BitBoxApp in order for the new settings to take effect.
```suggestion
#. Restart BitBoxApp in order for the new settings to take effect.
```

2024-01-02 01:36 UTC, kn0wmad commented on site/source/service-guides/bitcoin/bitcoin-integrations.rst
> +#. In the field “Enter the endpoint”, paste Tor address and the port from Electrs properties. For example: gwdllz5g7vky2q4gr45zGuvopjzf33czreca3a3exosftx72ekppkuqd.onion:50001
```suggestion
#. In the field “Enter the endpoint”, paste the Tor address and port from your server's Electrs > Properties page. For example: gwdllz5g7vky2q4gr45zGuvopjzf33czreca3a3exosftx72ekppkuqd.onion:50001
```

2024-01-02 01:36 UTC, kn0wmad commented on site/source/service-guides/bitcoin/bitcoin-integrations.rst
> +#. Click “Check”, you should be prompted with the message “Successfully established a connection”.
```suggestion
#. Click “Check,” and you will be prompted with the message “Successfully established a connection.”
```

2024-01-02 17:26 UTC, gStart9 commented on site/source/service-guides/bitcoin/bitcoin-integrations.rst
> +Guide adopted from `Shiftcrypto <https://shiftcrypto.support/help/en-us/14-privacy/29-how-to-connect-the-bitboxapp-to-my-own-full-node>`__.
```suggestion
Guide adapted from `Shiftcrypto<https://shiftcrypto.support/help/en-us/14-privacy/29-how-to-connect-the-bitboxapp-to-my-own-full-node>`__.
```

2024-01-02 18:20 UTC, kn0wmad approved these changes

2024-01-02 18:20 UTC, merged